#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Some relevant links
# Example of jupyter book in spanish: https://plantsandpython.github.io/PlantsAndPython/00_Opening_page.html
# Ejemplo de Jupyter book: https://github.com/Jero2760/jupyter-book-ejemplo
# Preguntas test: https://github.com/jmshea/jupyterquiz
# flashcards (anki): https://github.com/jmshea/jupytercards

# Book settings
title                       : Ingeniería del software  # The title of the book. Will be placed in the left navbar.
author                      : Ángel Lareo  # The author of the book
copyright                   : "2025"  # Copyright year to be placed in the footer
logo                        : logo_ings.png  # A path to the book logo. 
# Logo remade from: https://www.freepik.es/vector-gratis/composicion-linea-plana-desarrollo-software-caracteres-humanos-garabato-ventanas-computadora-lineas-codigo-engranajes-ilustracion-vectorial_70560967.htm

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/angellareo/manual-ings  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  # recursive_update: true
  config:
    html_context:
      default_mode: light
  extra_extensions:
    - sphinxcontrib.mermaid  
    # - sphinxcontrib.wavedrom
    # - sphinxcontrib.plantuml

parse:
  myst_enable_extensions:
    - footnote